title: Brie Doom
baseurl: ""
url: "https://briedoom.imustafin.tatar"

page_excerpts: true

author:
  name: Ilgiz Mustafin
  url: https://imustafin.tatar

social:
  name: Brie Doom
  links:
    - https://github.com/imustafin/brie_doom

plugins:
  - jekyll-tailwindcss
  - jekyll-seo-tag
  - jekyll-inline-svg

postcss:
  cache: false

svg:
  optimize: true

tag_page_layout: tag_page
tag_page_dir: tags

exclude:
  - README.md
  - brie_doom
  - docs
  - .github
  - .gitattributes
  - .gitignore
  - WrapC
  - wrap_sdl
  - Eiffel_19.05
  - dev.sh
  - utils
  # Ignore generated data
  - perf_plots
  - rakelib
  - COPYING
