title: Brie Doom
description: >-
  A Doom source port in Eiffel with Design by Contract.
baseurl: ""
url: "https://briedoom.imustafin.tatar"
github_username: imustafin

plugins:
  - jekyll-postcss


sass:
  implementation: sass-embedded
  sourcemap: never

exclude:
  # Speedup tailwind https://canolcer.com/post/jekyll-and-tailwind/
  - assets/css/tailwind.scss

  # Build job moves files from /site dir to the root,
  # so ignore everything from root
  - README.md
  - brie_doom
  - docs
  - .github
  - .gitattributes
  - .gitignore
  - WrapC
  - wrap_sdl
  - dev.sh
  - utils
  - tailwind.sh
  # Ignore js files
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - pages/.keep

keep_files:
  - assets/css/tailwind.css
