title: Brie Doom
description: >-
  A Doom source port in Eiffel with Design by Contract.
baseurl: ""
url: "https://imustafin.tatar"
github_username: imustafin

plugins:
  - jekyll-postcss

sass:
  implementation: sass-embedded
  sourcemap: never

exclude: []
