title: Brie Doom
baseurl: ""
url: "https://briedoom.imustafin.tatar"

page_excerpts: true

author:
  name: Ilgiz Mustafin
  url: https://imustafin.tatar

social:
  name: Brie Doom
  links:
    - https://github.com/imustafin/brie_doom

plugins:
  - jekyll-postcss
  - jekyll-seo-tag
  - jekyll-inline-svg

svg:
  optimize: true

sass:
  implementation: sass-embedded
  sourcemap: never

tag_page_layout: tag_page
tag_page_dir: tags

exclude:
  # Speedup tailwind https://canolcer.com/post/jekyll-and-tailwind/
  - assets/css/tailwind.scss

  # Build job moves files from /site dir to the root,
  # so ignore everything from root
  - README.md
  - brie_doom
  - docs
  - .github
  - .gitattributes
  - .gitignore
  - WrapC
  - wrap_sdl
  - dev.sh
  - utils
  - tailwind.sh
  # Ignore js files
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - yarn.lock
  - pages/.keep
  # Ignore generated data
  - perf_plots
  - rakelib
  - COPYING

keep_files:
  - assets/css/tailwind.css
