source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'jekyll', '~> 4.4', '>= 4.4.1'

# Temporary dep for jekyll
gem 'bigdecimal', '~> 3.0', '>= 3.0.2'

gem 'nokogiri', '~> 1.18', '>= 1.18.9'

gem "jekyll-tagging", "~> 1.1"

gem 'jekyll-seo-tag', '~> 2.8'

gem "numo-gnuplot", "~> 0.2.4"

gem "rake", "~> 13.0"

gem "jekyll-inline-svg", "~> 1.1"

gem 'eiffel_parser', github: 'imustafin/eiffel_parser', ref: '8dac0b1'
gem 'jekyll-tailwindcss', '~> 0.7'
