source "https://rubygems.org"

git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "jekyll", "~> 4.2.0"

gem "jekyll-postcss", "~> 0.4.1"

gem 'jekyll-sass-converter', github: 'jekyll/jekyll-sass-converter', ref: '5d130e8'

gem "nokogiri", "~> 1.12"

gem "jekyll-tagging", "~> 1.1"

gem "jekyll-seo-tag", github: 'jekyll/jekyll-seo-tag', ref: '36330e8'

gem 'sass-embedded', '~> 0.8.2'
